variables: 
  DOCKER_REGISTRY: 145504712931.dkr.ecr.us-west-2.amazonaws.com
  REPOSITORY_NAME: digitalbooking
  TEAM: remo
  APP: front

image: node:15

cache:
  paths:
    - front/proyecto/node_modules

stages:
  - test
  - build
  - package
  - deploy

test project:
  stage: test
  script:
    - cd front/proyecto
    - npm install
    - npm test

build project:
  stage: build
  script:
    - cd front/proyecto
    - CI=false npm run build
    - echo $CI_PIPELINE_IID > build/version.html
  artifacts:    
    paths:      
      - front/proyecto/build

build docker image:
    stage: package
    image:
      name: amazon/aws-cli
      entrypoint: [""]
    services:
      - docker:dind
    before_script:
      #- docker info
      - amazon-linux-extras install docker
      - aws --version
      - docker --version
    script:
      - echo $CI_REGISTRY
      - echo $CI_REGISTRY_USER
      - echo $CI_REGISTRY_PASSWORD
      - echo $CI_REGISTRY_IMAGE
      #- docker login gl.deitech.online:5050 -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
      #- ssh -T -p 26 -L 5050:gl.deitech.online:5050 user@gl.deitech.online
      #- echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
      #- docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID front/proyecto
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $DOCKER_REGISTRY #--region us-west-2
      - docker build -t $DOCKER_REGISTRY/$REPOSITORY_NAME:$TEAM:$APP:latest -t $DOCKER_REGISTRY/$REPOSITORY_NAME:$TEAM:$APP:$CI_PIPELINE_IID front/proyecto
      - docker image ls
      - docker push --all-tags $DOCKER_REGISTRY/$REPOSITORY_NAME #$DOCKER_REGISTRY/$REPOSITORY_NAME:$CI_PIPELINE_IID
      #- docker push --all-tags $CI_REGISTRY_IMAGE

# build docker image:
#   stage: docker
#   image: adoptopenjdk/openjdk11:alpine-jre
#   script:
#     - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
#     - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION ./back/digitalbooking/ # The first tag points to our latest image
#     - docker image ls
#     - docker push --all-tags $CI_REGISTRY_IMAGE


# .npm_build:  
#   image: node:10  
#   script:   
#     - npm install # Install all dependencies    
#     - npm build # yarn build:${APP_ENV} # Build command  
#   artifacts:    
#     paths:      
#       - ./build
#   only:    
#     refs:      
#       - main

# yarn_dev:  
#   extends: .yarn_build  
#   stage: build  
#   before_script:    
#     - export APP_ENV="dev"  
#   only:    
#     refs:      
#       - develop

# yarn_prod:  
#   extends: .yarn_build  
#   stage: build  
#   before_script:    
#     - export APP_ENV="prod"  
#   only:    
#     refs:      
#       - master