update token:
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  before_script:
    - aws --version
#    - yum install -y libtool.x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" 
  script:
    - echo $AWS_ECR_AUTH
    - USER=AWS
    - TOKEN=$(aws ecr get-login-password --region us-west-2)
    - echo $TOKEN
    - AUTH=$(echo "$USER:$TOKEN" | base64 | tr -d "\n")
    - echo $AUTH
    - echo $GITLAB_PERSONAL_ACCESS_TOKEN
    - |
      curl --location --request PUT 'https://gl.deitech.online/api/v4/projects/399/variables/AWS_ECR_AUTH' \
      --header 'Authorization: Bearer MWQBJQwxhGu-KBhj9zuQ' \
      --header 'Content-Type: application/x-www-form-urlencoded' \
      --form "value=$AUTH"
    #--data-urlencode 'value=$AUTH'
    #--silent --output /dev/null --show-error --fail