version: "3.8"
services:
  frontend:
    container_name: reactfrontend
    ports:
      - "80:80"
      - "443:443"
    image: $AWS_ECR_REGISTRY/$REPOSITORY_NAME:$TEAM-front-$CI_PIPELINE_IID"
  backend:
    container_name: springbootbackend
    ports:
      - "8080:8080"
    image: $AWS_ECR_REGISTRY/$REPOSITORY_NAME:$TEAM-back-$CI_PIPELINE_IID"