version: '3.8'
services:
  frontend:
    ports:
      - "80:80"
      - "443:443"
    image: "$AWS_ECR_REGISTRY/$REPOSITORY_NAME:$TEAM-front-$CI_PIPELINE_IID"
    links:
      - "backend"
  backend:
    ports:
      - "5000:5000"
    image: "$AWS_ECR_REGISTRY/$REPOSITORY_NAME:$TEAM-back-$CI_PIPELINE_IID"